#
#git:
#  depth: 1

language: node_js

before_install: nvm install node && npm install -g npm@latest
install: npm install

before_script: echo "before script"
script: echo "script build" && npm run build
after_script: echo "after script"
after_success: echo "after success"
after_failure: echo "after failure"

