#
#git:
#  depth: 1

language: node_js

before_install:
install: npm run i

before_script: echo "before script"
script: echo "script build" && npm run build
after_script: echo "after script"
after_success: echo "after success"
after_failure: echo "after failure"

